# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build & push Docker image  
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: yashaswini1234/spring-petclinic
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: remove old war/jar files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        port: 22
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          sudo rm -rf /home/ec2-user/github
          sudo rm -rf /home/ec2-user/apache-tomcat-9.0.52/webapps/spring-petclinic-2.5.0-SNAPSHOT.jar
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        port: 22
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "/home/runner/work/spring-petclinic/spring-petclinic/target/spring-petclinic-2.5.0-SNAPSHOT.jar"
        target: "/home/ec2-user/"
    - name: deploy jar file to tomcat server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        port: 22
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: sh tomcat-script.sh
  
      

   
